In [1]:
import pandas as pd

# Đọc dữ liệu đã làm sạch
df = pd.read_csv("../data/processed/houses_clean.csv")

# Kiểm tra kích thước
print("Kích thước dữ liệu:", df.shape)

# Xem 5 dòng đầu
display(df.head())

Kích thước dữ liệu: (9999, 19)

,name,description,property_type_name,province_name,district_name,ward_name,street_name,project_name,price,area,floor_count,frontage_width,house_depth,road_width,bedroom_count,bathroom_count,house_direction,balcony_direction,published_at
0,"Bán căn hộ dịch vụ 40 phòng, lợi nhuận ổn định...",Bán căn hộ dịch vụ mặt tiền 164 - 166 Nguyễn C...,Nhà,Hồ Chí Minh,Tân Phú,Tân Sơn Nhì,Nguyễn Cửu Đàm,Không rõ,3.500000e+10,130.0,3.0,8.0,15.0,6.0,3.0,2.0,Đông Bắc,Đông Bắc,2025-06-26T11:24:18
1,"Nguyễn Ngọc Lộc Q10, 5tầng BTCT hẻm 5m thông, ...",NGUYỄN NGỌC LỘC - HẺM XE HƠI 5M THÔNG - NHÀ 5 ...,Nhà,Hồ Chí Minh,10,14,Nguyễn Ngọc Lộc,Không rõ,6.500000e+09,24.0,5.0,3.7,15.0,6.0,3.0,4.0,Không rõ,Không rõ,2025-11-17T15:36:52.649000
2,"Nhà hẻm xe hơi ngay Aeon Mall Tân Phú, diện tí...",Nhà siêu hot ngay Aeon Mall Tân Phú đây! Diện ...,Nhà,Hồ Chí Minh,11,Không rõ,Không rõ,Không rõ,6.000000e+09,124.0,3.0,4.0,31.0,6.0,3.0,2.0,Không rõ,Không rõ,2025-09-16T09:56:07.702000
3,"Bán chung cư 4PN, 4WC tại Tôn Thất Thuyết, 64m...","Căn hộ chung cư nằm tại Đường Tôn Thất Thuyết,...",Căn hộ chung cư,Hồ Chí Minh,4,1,Tôn Thất Thuyết,Không rõ,7.500000e+09,64.0,3.0,4.9,15.0,6.0,4.0,4.0,Không rõ,Không rõ,2026-03-20T21:24:50.219000
4,"Bán gấp CC Tây Thạnh DT 72m2, 2 tỷ 7 TL 2PN 2W...","Bán chung cư Tây Thạnh, P. Tây Thạnh, Q. Tân P...",Căn hộ chung cư,Hồ Chí Minh,Tân Phú,Tây Thạnh,C8,Không rõ,2.700000e+09,72.0,3.0,4.9,15.0,6.0,2.0,2.0,Không rõ,Không rõ,2025-10-17T09:40:43.092000

In [2]:
# Hiển thị tên các cột
print("Các cột dữ liệu:")

for col in df.columns:
    print("-", col)

Các cột dữ liệu:
- name
- description
- property_type_name
- province_name
- district_name
- ward_name
- street_name
- project_name
- price
- area
- floor_count
- frontage_width
- house_depth
- road_width
- bedroom_count
- bathroom_count
- house_direction
- balcony_direction
- published_at

In [3]:
# Tạo tổng số phòng
df["total_rooms"] = (
    df["bedroom_count"] +
    df["bathroom_count"]
)

# Kiểm tra
display(
    df[
        [
            "bedroom_count",
            "bathroom_count",
            "total_rooms"
        ]
    ].head(10)
)

   bedroom_count  bathroom_count  total_rooms
0            3.0             2.0          5.0
1            3.0             4.0          7.0
2            3.0             2.0          5.0
3            4.0             4.0          8.0
4            2.0             2.0          4.0
5            2.0             2.0          4.0
6           32.0            33.0         65.0
7            3.0             2.0          5.0
8            3.0             2.0          5.0
9            1.0             2.0          3.0

In [4]:
# Tính diện tích trung bình cho mỗi phòng
df["area_per_room"] = (
    df["area"] /
    df["total_rooms"].replace(0, 1)
)

# Kiểm tra
display(
    df[
        [
            "area",
            "total_rooms",
            "area_per_room"
        ]
    ].head(10)
)

     area  total_rooms  area_per_room
0  130.00          5.0      26.000000
1   24.00          7.0       3.428571
2  124.00          5.0      24.800000
3   64.00          8.0       8.000000
4   72.00          4.0      18.000000
5   62.37          4.0      15.592500
6  162.20         65.0       2.495385
7   65.00          5.0      13.000000
8   95.00          5.0      19.000000
9   51.00          3.0      17.000000

In [5]:
# Xử lý ngày đăng tin
# Chuyển published_at sang kiểu ngày giờ
df["published_at"] = pd.to_datetime(
    df["published_at"],
    errors="coerce"
)

# Lấy năm đăng tin
df["published_year"] = df["published_at"].dt.year

# Lấy tháng đăng tin
df["published_month"] = df["published_at"].dt.month

# Lấy thứ trong tuần
df["published_dayofweek"] = df["published_at"].dt.dayofweek

# Kiểm tra
display(
    df[
        [
            "published_at",
            "published_year",
            "published_month",
            "published_dayofweek"
        ]
    ].head(10)
)

         published_at  published_year  published_month  published_dayofweek
0 2025-06-26 11:24:18          2025.0              6.0                  3.0
1                 NaT             NaN              NaN                  NaN
2                 NaT             NaN              NaN                  NaN
3                 NaT             NaN              NaN                  NaN
4                 NaT             NaN              NaN                  NaN
5                 NaT             NaN              NaN                  NaN
6                 NaT             NaN              NaN                  NaN
7                 NaT             NaN              NaN                  NaN
8                 NaT             NaN              NaN                  NaN
9                 NaT             NaN              NaN                  NaN

In [6]:
# tạo độ dài mô tả 
# Tính số ký tự trong mô tả
df["description_length"] = (
    df["description"].str.len()
)

# Kiểm tra
display(
    df[
        [
            "description",
            "description_length"
        ]
    ].head()
)

                                         description  description_length
0  Bán căn hộ dịch vụ mặt tiền 164 - 166 Nguyễn C...                 834
1  NGUYỄN NGỌC LỘC - HẺM XE HƠI 5M THÔNG - NHÀ 5 ...                 456
2  Nhà siêu hot ngay Aeon Mall Tân Phú đây! Diện ...                 320
3  Căn hộ chung cư nằm tại Đường Tôn Thất Thuyết,...                 695
4  Bán chung cư Tây Thạnh, P. Tây Thạnh, Q. Tân P...                 174

In [7]:
# tạo độ dài tên tin
# Tính số ký tự trong tên tin
df["name_length"] = df["name"].str.len()

# Kiểm tra
display(
    df[
        [
            "name",
            "name_length"
        ]
    ].head()
)

                                                name  name_length
0  Bán căn hộ dịch vụ 40 phòng, lợi nhuận ổn định...           97
1  Nguyễn Ngọc Lộc Q10, 5tầng BTCT hẻm 5m thông, ...           67
2  Nhà hẻm xe hơi ngay Aeon Mall Tân Phú, diện tí...           53
3  Bán chung cư 4PN, 4WC tại Tôn Thất Thuyết, 64m...           68
4  Bán gấp CC Tây Thạnh DT 72m2, 2 tỷ 7 TL 2PN 2W...           65

In [8]:
# Danh sách đặc trưng mới
new_features = [
    "total_rooms",
    "area_per_room",
    "published_year",
    "published_month",
    "published_dayofweek",
    "description_length",
    "name_length"
]

# Hiển thị thống kê
print("CÁC ĐẶC TRƯNG MỚI:")

display(
    df[new_features].describe()
)

CÁC ĐẶC TRƯNG MỚI:

,total_rooms,area_per_room,published_year,published_month,published_dayofweek,description_length,name_length
count,9999.000000,9999.000000,45.000000,45.000000,45.000000,9999.000000,9999.000000
mean,5.904990,20.336134,2025.866667,3.177778,2.822222,530.817682,79.957196
std,3.725983,32.665481,0.343776,2.699233,1.761829,332.946797,16.034706
min,2.000000,0.430000,2025.000000,1.000000,0.000000,49.000000,30.000000
25%,4.000000,8.888889,2026.000000,2.000000,2.000000,308.000000,69.000000
50%,5.000000,15.000000,2026.000000,3.000000,3.000000,451.000000,83.000000
75%,7.000000,21.500000,2026.000000,3.000000,4.000000,657.000000,94.000000
max,100.000000,1440.000000,2026.000000,12.000000,6.000000,3003.000000,108.000000

In [9]:
# Kiểm tra kích thước
print("Kích thước sau Feature Engineering:", df.shape)

# Kiểm tra dữ liệu thiếu
print("\nDữ liệu thiếu:")

missing = df.isnull().sum()

print(
    missing[missing > 0]
)

Kích thước sau Feature Engineering: (9999, 26)

Dữ liệu thiếu:
published_at           9954
published_year         9954
published_month        9954
published_dayofweek    9954
dtype: int64

In [10]:
# Hiển thị toàn bộ tên cột
print("DANH SÁCH CỘT SAU FEATURE ENGINEERING:")

for i, col in enumerate(df.columns):
    print(i, ":", col)

DANH SÁCH CỘT SAU FEATURE ENGINEERING:
0 : name
1 : description
2 : property_type_name
3 : province_name
4 : district_name
5 : ward_name
6 : street_name
7 : project_name
8 : price
9 : area
10 : floor_count
11 : frontage_width
12 : house_depth
13 : road_width
14 : bedroom_count
15 : bathroom_count
16 : house_direction
17 : balcony_direction
18 : published_at
19 : total_rooms
20 : area_per_room
21 : published_year
22 : published_month
23 : published_dayofweek
24 : description_length
25 : name_length

In [11]:
# chuẩn bị dữ liệu trước khi train
# Tách biến mục tiêu
y = df["price"]

# Tạo danh sách các cột không dùng làm đầu vào
drop_cols = [
    "price",
    "published_at"
]

# Tạo dữ liệu đầu vào
X = df.drop(columns=drop_cols)

# Kiểm tra
print("Kích thước X:", X.shape)
print("Kích thước y:", y.shape)

Kích thước X: (9999, 24)
Kích thước y: (9999,)

In [12]:
# Xem các cột đầu vào
print("CÁC CỘT ĐẦU VÀO X:")

for col in X.columns:
    print("-", col)

# Xem biến mục tiêu
print("\nBIẾN MỤC TIÊU:")
print("price")

CÁC CỘT ĐẦU VÀO X:
- name
- description
- property_type_name
- province_name
- district_name
- ward_name
- street_name
- project_name
- area
- floor_count
- frontage_width
- house_depth
- road_width
- bedroom_count
- bathroom_count
- house_direction
- balcony_direction
- total_rooms
- area_per_room
- published_year
- published_month
- published_dayofweek
- description_length
- name_length

BIẾN MỤC TIÊU:
price